# Generated by Django 4.2.7 on 2023-11-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author_alter_post_body_alter_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='thumbnail/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
